name: Build Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Set up Android SDK
      uses: r0x0r/android-sdk-setup@v1
      with:
        api-level: '30'
        components: 'platform-tools,build-tools;30.0.3'

    - name: Set permissions for gradlew
      run: chmod +x ./gradlew

    - name: Build mod
      run: ./gradlew deploy
